`timescale 1ns / 1ps
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Apr 15 2023 17:22:42 IST (Apr 15 2023 11:52:42 UTC)

// Verification Directory fv/MESI_FSM 

module MESI_FSM(clk, resetn, Core_Op, PrHlt, pr_addr, Cache_output,
     Cache_input, bus_in, bus_out, flag_in, flag_out);
  input clk, resetn, Core_Op, flag_in;
  input [3:0] pr_addr;
  input [7:0] Cache_input;
  input [16:0] bus_in;
  output PrHlt, flag_out;
  output [7:0] Cache_output;
  output [16:0] bus_out;
  wire clk, resetn, Core_Op, flag_in;
  wire [3:0] pr_addr;
  wire [7:0] Cache_input;
  wire [16:0] bus_in;
  wire PrHlt, flag_out;
  wire [7:0] Cache_output;
  wire [16:0] bus_out;
  wire [7:0] \L1_Cache[1] ;
  wire [7:0] \L1_Cache[3] ;
  wire [1:0] \tag_directory[1] ;
  wire [1:0] \tag_directory[3] ;
  wire [7:0] \L1_Cache[0] ;
  wire [7:0] \L1_Cache[2] ;
  wire [1:0] \tag_directory[2] ;
  wire [1:0] \tag_directory[0] ;
  wire [1:0] \Cache_Status[0] ;
  wire [1:0] \Cache_Status[1] ;
  wire [1:0] \Cache_Status[2] ;
  wire [1:0] \Cache_Status[3] ;
  wire [3:0] invalid_state_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_13, n_14, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_26, n_29, n_30, n_31, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_53, n_54, n_55, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_159, n_160;
  wire n_161, n_162, n_163, n_164, n_165, n_166, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_233, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_242, n_243, n_244, n_245;
  wire n_246, n_247, n_248, n_250, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_260, n_261, n_262, n_263, n_264;
  wire n_265, n_266, n_267, n_268, n_269, n_270, n_271, n_272;
  wire n_273, n_274, n_275, n_276, n_277, n_278, n_279, n_280;
  wire n_281, n_282, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352;
  wire n_353, n_354, n_355, n_356, n_357, n_358, n_359, n_360;
  wire n_361, n_362, n_363, n_364, n_365, n_366, n_367, n_368;
  wire n_369, n_370, n_371, n_372, n_373, n_374, n_375, n_376;
  wire n_377, n_378, n_379, n_380, n_381, n_382, n_383, n_384;
  wire n_385, n_386, n_387, n_388, n_389, n_390, n_391, n_392;
  wire n_393, n_394, n_395, n_396, n_397, n_398, n_399, n_400;
  wire n_401, n_402, n_403, n_404, n_405, n_406, n_407, n_408;
  wire n_409, n_410, n_411, n_412, n_413, n_414, n_415, n_416;
  wire n_417, n_418, n_419, n_444, n_445, n_446, n_447, n_448;
  wire n_449, n_450, n_451, n_452, n_453, n_454;
  assign flag_out = 1'b0;
  assign bus_out[15] = 1'b0;
  assign bus_out[16] = 1'b0;
  DFQM1RA \L1_Cache_reg[1][5] (.CK (clk), .D (n_411), .Q
       (\L1_Cache[1] [5]));
  DFQM1RA \L1_Cache_reg[1][1] (.CK (clk), .D (n_415), .Q
       (\L1_Cache[1] [1]));
  DFQM1RA \L1_Cache_reg[1][2] (.CK (clk), .D (n_414), .Q
       (\L1_Cache[1] [2]));
  DFQM1RA \L1_Cache_reg[1][3] (.CK (clk), .D (n_413), .Q
       (\L1_Cache[1] [3]));
  DFQM1RA \L1_Cache_reg[1][4] (.CK (clk), .D (n_412), .Q
       (\L1_Cache[1] [4]));
  DFQM1RA \L1_Cache_reg[1][6] (.CK (clk), .D (n_419), .Q
       (\L1_Cache[1] [6]));
  DFQM1RA \L1_Cache_reg[1][7] (.CK (clk), .D (n_410), .Q
       (\L1_Cache[1] [7]));
  DFQM1RA \L1_Cache_reg[3][0] (.CK (clk), .D (n_405), .Q
       (\L1_Cache[3] [0]));
  DFQM1RA \L1_Cache_reg[3][6] (.CK (clk), .D (n_395), .Q
       (\L1_Cache[3] [6]));
  DFQM1RA \L1_Cache_reg[3][3] (.CK (clk), .D (n_408), .Q
       (\L1_Cache[3] [3]));
  DFQM1RA \L1_Cache_reg[3][4] (.CK (clk), .D (n_399), .Q
       (\L1_Cache[3] [4]));
  DFQM1RA \L1_Cache_reg[3][5] (.CK (clk), .D (n_397), .Q
       (\L1_Cache[3] [5]));
  DFQM1RA \L1_Cache_reg[3][1] (.CK (clk), .D (n_403), .Q
       (\L1_Cache[3] [1]));
  DFQM1RA \L1_Cache_reg[3][7] (.CK (clk), .D (n_418), .Q
       (\L1_Cache[3] [7]));
  DFQM1RA \L1_Cache_reg[1][0] (.CK (clk), .D (n_417), .Q
       (\L1_Cache[1] [0]));
  DFQM1RA \L1_Cache_reg[3][2] (.CK (clk), .D (n_401), .Q
       (\L1_Cache[3] [2]));
  DFQM2RA \tag_directory_reg[1][0] (.CK (clk), .D (n_387), .Q
       (\tag_directory[1] [0]));
  DFQM2RA \tag_directory_reg[3][0] (.CK (clk), .D (n_378), .Q
       (\tag_directory[3] [0]));
  DFQM1RA \L1_Cache_reg[0][6] (.CK (clk), .D (n_374), .Q
       (\L1_Cache[0] [6]));
  DFQM2RA \tag_directory_reg[1][1] (.CK (clk), .D (n_384), .Q
       (\tag_directory[1] [1]));
  DFQM1RA \L1_Cache_reg[0][0] (.CK (clk), .D (n_379), .Q
       (\L1_Cache[0] [0]));
  DFQM1RA \L1_Cache_reg[0][1] (.CK (clk), .D (n_377), .Q
       (\L1_Cache[0] [1]));
  DFQM1RA \L1_Cache_reg[2][7] (.CK (clk), .D (n_364), .Q
       (\L1_Cache[2] [7]));
  DFQM1RA \L1_Cache_reg[0][4] (.CK (clk), .D (n_376), .Q
       (\L1_Cache[0] [4]));
  DFQM1RA \L1_Cache_reg[0][5] (.CK (clk), .D (n_375), .Q
       (\L1_Cache[0] [5]));
  DFQM2RA \tag_directory_reg[3][1] (.CK (clk), .D (n_349), .Q
       (\tag_directory[3] [1]));
  DFQM1RA \L1_Cache_reg[0][2] (.CK (clk), .D (n_393), .Q
       (\L1_Cache[0] [2]));
  DFQM1RA \L1_Cache_reg[0][3] (.CK (clk), .D (n_366), .Q
       (\L1_Cache[0] [3]));
  DFQM1RA \L1_Cache_reg[0][7] (.CK (clk), .D (n_381), .Q
       (\L1_Cache[0] [7]));
  DFQM1RA \L1_Cache_reg[2][0] (.CK (clk), .D (n_373), .Q
       (\L1_Cache[2] [0]));
  DFQM1RA \L1_Cache_reg[2][1] (.CK (clk), .D (n_372), .Q
       (\L1_Cache[2] [1]));
  DFQM1RA \L1_Cache_reg[2][3] (.CK (clk), .D (n_369), .Q
       (\L1_Cache[2] [3]));
  DFQM1RA \L1_Cache_reg[2][4] (.CK (clk), .D (n_356), .Q
       (\L1_Cache[2] [4]));
  DFQM1RA \L1_Cache_reg[2][5] (.CK (clk), .D (n_367), .Q
       (\L1_Cache[2] [5]));
  OAI21M2R g22322__2398(.A1 (n_394), .A2 (n_416), .B (n_354), .Z
       (n_419));
  OAI21M2R g22331__5107(.A1 (n_409), .A2 (n_406), .B (n_385), .Z
       (n_418));
  OAI21M2R g22316__6260(.A1 (n_404), .A2 (n_416), .B (n_363), .Z
       (n_417));
  OAI21M2R g22317__4319(.A1 (n_402), .A2 (n_416), .B (n_359), .Z
       (n_415));
  OAI21M2R g22318__8428(.A1 (n_400), .A2 (n_416), .B (n_358), .Z
       (n_414));
  OAI21M2R g22319__5526(.A1 (n_407), .A2 (n_416), .B (n_368), .Z
       (n_413));
  OAI21M2R g22320__6783(.A1 (n_398), .A2 (n_416), .B (n_357), .Z
       (n_412));
  OAI21M2R g22321__3680(.A1 (n_396), .A2 (n_416), .B (n_355), .Z
       (n_411));
  OAI21M2R g22323__1617(.A1 (n_409), .A2 (n_416), .B (n_353), .Z
       (n_410));
  OAI21M2R g22330__2802(.A1 (n_407), .A2 (n_406), .B (n_346), .Z
       (n_408));
  OAI21M2R g22324__1705(.A1 (n_404), .A2 (n_406), .B (n_352), .Z
       (n_405));
  OAI21M2R g22325__5122(.A1 (n_402), .A2 (n_406), .B (n_351), .Z
       (n_403));
  OAI21M2R g22326__8246(.A1 (n_400), .A2 (n_406), .B (n_350), .Z
       (n_401));
  OAI21M2R g22327__7098(.A1 (n_398), .A2 (n_406), .B (n_392), .Z
       (n_399));
  OAI21M2R g22328__6131(.A1 (n_396), .A2 (n_406), .B (n_391), .Z
       (n_397));
  OAI21M2R g22329__1881(.A1 (n_394), .A2 (n_406), .B (n_386), .Z
       (n_395));
  DFQM1RA \L1_Cache_reg[2][6] (.CK (clk), .D (n_365), .Q
       (\L1_Cache[2] [6]));
  DFQM1RA \L1_Cache_reg[2][2] (.CK (clk), .D (n_370), .Q
       (\L1_Cache[2] [2]));
  DFQM2RA \tag_directory_reg[2][0] (.CK (clk), .D (n_333), .Q
       (\tag_directory[2] [0]));
  DFQM2RA \tag_directory_reg[0][0] (.CK (clk), .D (n_336), .Q
       (\tag_directory[0] [0]));
  DFQM1RA \Cache_output_reg[6] (.CK (clk), .D (n_343), .Q
       (Cache_output[6]));
  DFQM1RA \Cache_output_reg[2] (.CK (clk), .D (n_342), .Q
       (Cache_output[2]));
  DFQM2RA \tag_directory_reg[0][1] (.CK (clk), .D (n_335), .Q
       (\tag_directory[0] [1]));
  DFQM2RA \tag_directory_reg[2][1] (.CK (clk), .D (n_338), .Q
       (\tag_directory[2] [1]));
  DFQM1RA \Cache_output_reg[7] (.CK (clk), .D (n_344), .Q
       (Cache_output[7]));
  DFQM1RA \Cache_output_reg[1] (.CK (clk), .D (n_341), .Q
       (Cache_output[1]));
  DFQM1RA \Cache_output_reg[4] (.CK (clk), .D (n_339), .Q
       (Cache_output[4]));
  DFQM1RA \Cache_output_reg[5] (.CK (clk), .D (n_345), .Q
       (Cache_output[5]));
  DFQM1RA \Cache_output_reg[0] (.CK (clk), .D (n_337), .Q
       (Cache_output[0]));
  DFQM1RA \Cache_output_reg[3] (.CK (clk), .D (n_340), .Q
       (Cache_output[3]));
  OAI21B20M2R g22338__5115(.B (n_311), .NA1 (\L1_Cache[0] [2]), .NA2
       (n_380), .Z (n_393));
  AOI221M2R g22385__7482(.A1 (n_390), .A2 (Cache_input[4]), .B1
       (n_389), .B2 (\L1_Cache[3] [4]), .C (n_388), .Z (n_392));
  AOI221M2R g22386__4733(.A1 (n_390), .A2 (Cache_input[5]), .B1
       (n_389), .B2 (\L1_Cache[3] [5]), .C (n_388), .Z (n_391));
  MOAI22M2RA g22334__6161(.A1 (n_287), .A2 (n_383), .B1 (n_382), .B2
       (\tag_directory[1] [0]), .Z (n_387));
  AOI221M2R g22387__9315(.A1 (n_390), .A2 (Cache_input[6]), .B1
       (n_389), .B2 (\L1_Cache[3] [6]), .C (n_388), .Z (n_386));
  AOI221M2R g22388__9945(.A1 (n_390), .A2 (Cache_input[7]), .B1
       (n_389), .B2 (\L1_Cache[3] [7]), .C (n_388), .Z (n_385));
  MOAI22M2RA g22335__2883(.A1 (n_301), .A2 (n_383), .B1 (n_382), .B2
       (\tag_directory[1] [1]), .Z (n_384));
  OAI21B20M2R g22336__2346(.B (n_330), .NA1 (\L1_Cache[0] [7]), .NA2
       (n_380), .Z (n_381));
  OAI21B20M2R g22337__1666(.B (n_315), .NA1 (\L1_Cache[0] [0]), .NA2
       (n_380), .Z (n_379));
  MOAI22M2RA g22333__7410(.A1 (n_283), .A2 (n_348), .B1 (n_347), .B2
       (\tag_directory[3] [0]), .Z (n_378));
  OAI21B20M2R g22339__6417(.B (n_313), .NA1 (\L1_Cache[0] [1]), .NA2
       (n_380), .Z (n_377));
  OAI21B20M2R g22341__5477(.B (n_307), .NA1 (\L1_Cache[0] [4]), .NA2
       (n_380), .Z (n_376));
  OAI21B20M2R g22342__2398(.B (n_305), .NA1 (\L1_Cache[0] [5]), .NA2
       (n_380), .Z (n_375));
  OAI21B20M2R g22343__5107(.B (n_321), .NA1 (\L1_Cache[0] [6]), .NA2
       (n_380), .Z (n_374));
  OAI21B20M2R g22344__6260(.B (n_329), .NA1 (\L1_Cache[2] [0]), .NA2
       (n_371), .Z (n_373));
  OAI21B20M2R g22362__4319(.B (n_325), .NA1 (\L1_Cache[2] [1]), .NA2
       (n_371), .Z (n_372));
  OAI21B20M2R g22363__8428(.B (n_331), .NA1 (\L1_Cache[2] [2]), .NA2
       (n_371), .Z (n_370));
  OAI21B20M2R g22364__5526(.B (n_323), .NA1 (\L1_Cache[2] [3]), .NA2
       (n_371), .Z (n_369));
  AOI221M2R g22377__6783(.A1 (n_362), .A2 (Cache_input[3]), .B1
       (n_361), .B2 (\L1_Cache[1] [3]), .C (n_360), .Z (n_368));
  OAI21B20M2R g22366__3680(.B (n_324), .NA1 (\L1_Cache[2] [5]), .NA2
       (n_371), .Z (n_367));
  OAI21B20M2R g22340__1617(.B (n_309), .NA1 (\L1_Cache[0] [3]), .NA2
       (n_380), .Z (n_366));
  OAI21B20M2R g22367__2802(.B (n_303), .NA1 (\L1_Cache[2] [6]), .NA2
       (n_371), .Z (n_365));
  OAI21B20M2R g22368__1705(.B (n_317), .NA1 (\L1_Cache[2] [7]), .NA2
       (n_371), .Z (n_364));
  AOI221M2R g22373__5122(.A1 (n_362), .A2 (Cache_input[0]), .B1
       (n_361), .B2 (\L1_Cache[1] [0]), .C (n_360), .Z (n_363));
  AOI221M2R g22374__8246(.A1 (n_362), .A2 (Cache_input[1]), .B1
       (n_361), .B2 (\L1_Cache[1] [1]), .C (n_360), .Z (n_359));
  AOI221M2R g22375__7098(.A1 (n_362), .A2 (Cache_input[2]), .B1
       (n_361), .B2 (\L1_Cache[1] [2]), .C (n_360), .Z (n_358));
  AOI221M2R g22376__6131(.A1 (n_362), .A2 (Cache_input[4]), .B1
       (n_361), .B2 (\L1_Cache[1] [4]), .C (n_360), .Z (n_357));
  OAI21B20M2R g22365__1881(.B (n_322), .NA1 (\L1_Cache[2] [4]), .NA2
       (n_371), .Z (n_356));
  AOI221M2R g22378__5115(.A1 (n_362), .A2 (Cache_input[5]), .B1
       (n_361), .B2 (\L1_Cache[1] [5]), .C (n_360), .Z (n_355));
  AOI221M2R g22379__7482(.A1 (n_362), .A2 (Cache_input[6]), .B1
       (n_361), .B2 (\L1_Cache[1] [6]), .C (n_360), .Z (n_354));
  AOI221M2R g22380__4733(.A1 (n_362), .A2 (Cache_input[7]), .B1
       (n_361), .B2 (\L1_Cache[1] [7]), .C (n_360), .Z (n_353));
  AOI221M2R g22381__6161(.A1 (n_390), .A2 (Cache_input[0]), .B1
       (n_389), .B2 (\L1_Cache[3] [0]), .C (n_388), .Z (n_352));
  AOI221M2R g22382__9315(.A1 (n_390), .A2 (Cache_input[1]), .B1
       (n_389), .B2 (\L1_Cache[3] [1]), .C (n_388), .Z (n_351));
  AOI221M2R g22383__9945(.A1 (n_390), .A2 (Cache_input[2]), .B1
       (n_389), .B2 (\L1_Cache[3] [2]), .C (n_388), .Z (n_350));
  MOAI22M2RA g22332__2883(.A1 (n_285), .A2 (n_348), .B1 (n_347), .B2
       (\tag_directory[3] [1]), .Z (n_349));
  AOI221M2R g22384__2346(.A1 (n_390), .A2 (Cache_input[3]), .B1
       (n_389), .B2 (\L1_Cache[3] [3]), .C (n_388), .Z (n_346));
  CKND2M2R g22397__1666(.A (n_253), .B (n_294), .Z (n_345));
  CKND2M2R g22398__7410(.A (n_300), .B (n_264), .Z (n_344));
  CKND2M2R g22396__6417(.A (n_263), .B (n_293), .Z (n_343));
  CKND2M2R g22399__5477(.A (n_257), .B (n_258), .Z (n_342));
  CKND2M2R g22400__2398(.A (n_256), .B (n_288), .Z (n_341));
  CKND2M2R g22401__5107(.A (n_255), .B (n_299), .Z (n_340));
  DFQM1RA \bus_out_reg[0] (.CK (clk), .D (n_289), .Q (bus_out[0]));
  DFQM1RA \bus_out_reg[1] (.CK (clk), .D (n_291), .Q (bus_out[1]));
  DFQM1RA \bus_out_reg[2] (.CK (clk), .D (n_292), .Q (bus_out[2]));
  DFQM1RA \bus_out_reg[3] (.CK (clk), .D (n_276), .Q (bus_out[3]));
  DFQM2RA \Cache_Status_reg[0][0] (.CK (clk), .D (n_274), .Q
       (\Cache_Status[0] [0]));
  DFQM1RA \bus_out_reg[7] (.CK (clk), .D (n_277), .Q (bus_out[7]));
  DFQM1RA \bus_out_reg[5] (.CK (clk), .D (n_279), .Q (bus_out[5]));
  DFQM2RA \Cache_Status_reg[1][1] (.CK (clk), .D (n_268), .Q
       (\Cache_Status[1] [1]));
  CKND2M2R g22402__6260(.A (n_254), .B (n_297), .Z (n_339));
  OAI21B20M2R g22372__4319(.B (n_247), .NA1 (\tag_directory[2] [1]),
       .NA2 (n_332), .Z (n_338));
  ND4M2R g22418__8428(.A (n_248), .B (n_237), .C (n_170), .D (n_159),
       .Z (n_337));
  OAI21B20M2R g22369__5526(.B (n_246), .NA1 (\tag_directory[0] [0]),
       .NA2 (n_334), .Z (n_336));
  OAI21B20M2R g22370__6783(.B (n_245), .NA1 (\tag_directory[0] [1]),
       .NA2 (n_334), .Z (n_335));
  OAI21B20M2R g22371__3680(.B (n_241), .NA1 (\tag_directory[2] [0]),
       .NA2 (n_332), .Z (n_333));
  DFQM2RA \Cache_Status_reg[1][0] (.CK (clk), .D (n_273), .Q
       (\Cache_Status[1] [0]));
  DFQM2RA \Cache_Status_reg[2][0] (.CK (clk), .D (n_270), .Q
       (\Cache_Status[2] [0]));
  DFQM2RA \Cache_Status_reg[3][0] (.CK (clk), .D (n_266), .Q
       (\Cache_Status[3] [0]));
  DFQM1RA \bus_out_reg[6] (.CK (clk), .D (n_278), .Q (bus_out[6]));
  DFQM1RA \bus_out_reg[4] (.CK (clk), .D (n_280), .Q (bus_out[4]));
  DFQM2RA \Cache_Status_reg[0][1] (.CK (clk), .D (n_260), .Q
       (\Cache_Status[0] [1]));
  DFQM2RA \Cache_Status_reg[2][1] (.CK (clk), .D (n_271), .Q
       (\Cache_Status[2] [1]));
  DFQM2RA \Cache_Status_reg[3][1] (.CK (clk), .D (n_275), .Q
       (\Cache_Status[3] [1]));
  AOI221M2R g22421__1617(.A1 (n_328), .A2 (Cache_input[2]), .B1
       (n_327), .B2 (n_310), .C (n_326), .Z (n_331));
  AOI221M2R g22412__2802(.A1 (n_320), .A2 (Cache_input[7]), .B1
       (n_319), .B2 (n_316), .C (n_318), .Z (n_330));
  AOI221M2R g22419__1705(.A1 (n_328), .A2 (Cache_input[0]), .B1
       (n_327), .B2 (n_314), .C (n_326), .Z (n_329));
  AOI221M2R g22420__5122(.A1 (n_328), .A2 (Cache_input[1]), .B1
       (n_327), .B2 (n_312), .C (n_326), .Z (n_325));
  AOI221M2R g22424__8246(.A1 (n_328), .A2 (Cache_input[5]), .B1
       (n_327), .B2 (n_304), .C (n_326), .Z (n_324));
  AOI221M2R g22422__7098(.A1 (n_328), .A2 (Cache_input[3]), .B1
       (n_327), .B2 (n_308), .C (n_326), .Z (n_323));
  AOI221M2R g22423__6131(.A1 (n_328), .A2 (Cache_input[4]), .B1
       (n_327), .B2 (n_306), .C (n_326), .Z (n_322));
  DFQM2RA \invalid_state_counter_reg[3] (.CK (clk), .D (n_236), .Q
       (invalid_state_counter[3]));
  AOI221M2R g22433__1881(.A1 (n_320), .A2 (Cache_input[6]), .B1
       (n_319), .B2 (n_302), .C (n_318), .Z (n_321));
  AOI221M2R g22426__5115(.A1 (n_328), .A2 (Cache_input[7]), .B1
       (n_327), .B2 (n_316), .C (n_326), .Z (n_317));
  AOI221M2R g22427__7482(.A1 (n_320), .A2 (Cache_input[0]), .B1
       (n_319), .B2 (n_314), .C (n_318), .Z (n_315));
  AOI221M2R g22428__4733(.A1 (n_320), .A2 (Cache_input[1]), .B1
       (n_319), .B2 (n_312), .C (n_318), .Z (n_313));
  AOI221M2R g22429__6161(.A1 (n_320), .A2 (Cache_input[2]), .B1
       (n_319), .B2 (n_310), .C (n_318), .Z (n_311));
  AOI221M2R g22430__9315(.A1 (n_320), .A2 (Cache_input[3]), .B1
       (n_319), .B2 (n_308), .C (n_318), .Z (n_309));
  AOI221M2R g22431__9945(.A1 (n_320), .A2 (Cache_input[4]), .B1
       (n_319), .B2 (n_306), .C (n_318), .Z (n_307));
  AOI221M2R g22432__2883(.A1 (n_320), .A2 (Cache_input[5]), .B1
       (n_319), .B2 (n_304), .C (n_318), .Z (n_305));
  AOI221M2R g22425__2346(.A1 (n_328), .A2 (Cache_input[6]), .B1
       (n_327), .B2 (n_302), .C (n_326), .Z (n_303));
  AOI21M2R g22392__1666(.A1 (n_286), .A2 (bus_in[11]), .B (n_284), .Z
       (n_301));
  AOI222M1RA g22463__7410(.A1 (n_295), .A2 (\L1_Cache[3] [7]), .B1
       (n_261), .B2 (\L1_Cache[2] [7]), .C1 (n_298), .C2
       (\L1_Cache[1] [7]), .Z (n_300));
  AOI221M2R g22464__6417(.A1 (n_296), .A2 (Cache_output[3]), .B1
       (n_298), .B2 (\L1_Cache[1] [3]), .C (n_197), .Z (n_299));
  AOI221M2R g22465__5477(.A1 (n_296), .A2 (Cache_output[4]), .B1
       (n_295), .B2 (\L1_Cache[3] [4]), .C (n_198), .Z (n_297));
  AOI221M2R g22466__2398(.A1 (n_296), .A2 (Cache_output[5]), .B1
       (n_295), .B2 (\L1_Cache[3] [5]), .C (n_192), .Z (n_294));
  AOI221M2R g22467__5107(.A1 (n_296), .A2 (Cache_output[6]), .B1
       (n_298), .B2 (\L1_Cache[1] [6]), .C (n_193), .Z (n_293));
  ND4M2R g22389__6260(.A (n_226), .B (n_200), .C (n_149), .D (n_290),
       .Z (n_292));
  ND4M2R g22390__4319(.A (n_214), .B (n_215), .C (n_156), .D (n_290),
       .Z (n_291));
  ND4M2R g22391__8428(.A (n_216), .B (n_217), .C (n_150), .D (n_290),
       .Z (n_289));
  AOI221M2R g22462__5526(.A1 (n_296), .A2 (Cache_output[1]), .B1
       (n_295), .B2 (\L1_Cache[3] [1]), .C (n_190), .Z (n_288));
  AOI21M2R g22393__6783(.A1 (n_286), .A2 (bus_in[10]), .B (n_281), .Z
       (n_287));
  AOI21M2R g22394__3680(.A1 (n_282), .A2 (bus_in[11]), .B (n_284), .Z
       (n_285));
  AOI21M2R g22395__1617(.A1 (n_282), .A2 (bus_in[10]), .B (n_281), .Z
       (n_283));
  ND4M2R g22413__2802(.A (n_201), .B (n_227), .C (n_148), .D (n_290),
       .Z (n_280));
  ND4M2R g22414__1705(.A (n_213), .B (n_199), .C (n_153), .D (n_290),
       .Z (n_279));
  ND4M2R g22415__5122(.A (n_222), .B (n_220), .C (n_154), .D (n_290),
       .Z (n_278));
  ND4M2R g22416__8246(.A (n_210), .B (n_225), .C (n_155), .D (n_290),
       .Z (n_277));
  ND4M2R g22434__7098(.A (n_218), .B (n_212), .C (n_147), .D (n_290),
       .Z (n_276));
  OAI211M2R g22435__6131(.A1 (n_98), .A2 (n_185), .B (n_265), .C
       (n_181), .Z (n_275));
  OAI211M2R g22437__1881(.A1 (n_272), .A2 (n_202), .B (n_448), .C
       (n_203), .Z (n_274));
  OAI211M2R g22438__5115(.A1 (n_272), .A2 (n_204), .B (n_267), .C
       (n_205), .Z (n_273));
  OAI211M2R g22439__7482(.A1 (n_101), .A2 (n_186), .B (n_269), .C
       (n_178), .Z (n_271));
  OAI211M2R g22440__4733(.A1 (n_272), .A2 (n_206), .B (n_269), .C
       (n_207), .Z (n_270));
  OAI211M2R g22441__6161(.A1 (n_96), .A2 (n_187), .B (n_267), .C
       (n_180), .Z (n_268));
  OAI211M2R g22442__9315(.A1 (n_272), .A2 (n_208), .B (n_265), .C
       (n_209), .Z (n_266));
  AOI221M2R g22461__9945(.A1 (n_296), .A2 (Cache_output[7]), .B1
       (n_262), .B2 (\L1_Cache[0] [7]), .C (n_191), .Z (n_264));
  AOI222M1RA g22460__2883(.A1 (n_262), .A2 (\L1_Cache[0] [6]), .B1
       (n_295), .B2 (\L1_Cache[3] [6]), .C1 (n_261), .C2
       (\L1_Cache[2] [6]), .Z (n_263));
  OAI211M2R g22436__2346(.A1 (n_100), .A2 (n_188), .B (n_448), .C
       (n_177), .Z (n_260));
  AOI221M2R g22454__1666(.A1 (n_296), .A2 (Cache_output[2]), .B1
       (n_295), .B2 (\L1_Cache[3] [2]), .C (n_189), .Z (n_258));
  AOI222M1RA g22455__7410(.A1 (n_262), .A2 (\L1_Cache[0] [2]), .B1
       (n_298), .B2 (\L1_Cache[1] [2]), .C1 (n_261), .C2
       (\L1_Cache[2] [2]), .Z (n_257));
  AOI222M1RA g22456__6417(.A1 (n_262), .A2 (\L1_Cache[0] [1]), .B1
       (n_298), .B2 (\L1_Cache[1] [1]), .C1 (n_261), .C2
       (\L1_Cache[2] [1]), .Z (n_256));
  AOI222M1RA g22457__5477(.A1 (n_262), .A2 (\L1_Cache[0] [3]), .B1
       (n_295), .B2 (\L1_Cache[3] [3]), .C1 (n_261), .C2
       (\L1_Cache[2] [3]), .Z (n_255));
  AOI222M1RA g22458__2398(.A1 (n_262), .A2 (\L1_Cache[0] [4]), .B1
       (n_261), .B2 (\L1_Cache[2] [4]), .C1 (n_298), .C2
       (\L1_Cache[1] [4]), .Z (n_254));
  AOI222M1RA g22459__5107(.A1 (n_262), .A2 (\L1_Cache[0] [5]), .B1
       (n_261), .B2 (\L1_Cache[2] [5]), .C1 (n_298), .C2
       (\L1_Cache[1] [5]), .Z (n_253));
  OAI21M2R g22445__6260(.A1 (n_22), .A2 (n_250), .B (n_445), .Z
       (n_382));
  OAI21M2R g22444__4319(.A1 (n_18), .A2 (n_252), .B (n_444), .Z
       (n_347));
  OAI21M2R g22451__8428(.A1 (n_23), .A2 (n_252), .B (n_444), .Z
       (n_389));
  OAI21M2R g22453__5526(.A1 (n_24), .A2 (n_250), .B (n_445), .Z
       (n_361));
  AOI22M2R g22492__6783(.A1 (n_262), .A2 (\L1_Cache[0] [0]), .B1
       (n_298), .B2 (\L1_Cache[1] [0]), .Z (n_248));
  AOI32M2R g22470__3680(.A1 (n_240), .A2 (n_239), .A3 (bus_in[11]), .B1
       (n_284), .B2 (n_238), .Z (n_247));
  AOI32M2R g22471__1617(.A1 (n_244), .A2 (n_243), .A3 (bus_in[10]), .B1
       (n_281), .B2 (n_242), .Z (n_246));
  AOI32M2R g22472__2802(.A1 (n_244), .A2 (n_243), .A3 (bus_in[11]), .B1
       (n_284), .B2 (n_242), .Z (n_245));
  AOI32M2R g22469__1705(.A1 (n_240), .A2 (n_239), .A3 (bus_in[10]), .B1
       (n_281), .B2 (n_238), .Z (n_241));
  AOI22M2R g22491__5122(.A1 (n_261), .A2 (\L1_Cache[2] [0]), .B1
       (n_295), .B2 (\L1_Cache[3] [0]), .Z (n_237));
  OAI21M2R g22473__8246(.A1 (n_243), .A2 (n_233), .B (n_446), .Z
       (n_334));
  MOAI22M2RA g22417__7098(.A1 (n_228), .A2 (n_2), .B1 (n_183), .B2
       (invalid_state_counter[3]), .Z (n_236));
  OAI21M2R g22443__6131(.A1 (n_239), .A2 (n_235), .B (n_447), .Z
       (n_332));
  DFQM2RA \invalid_state_counter_reg[2] (.CK (clk), .D (n_229), .Q
       (invalid_state_counter[2]));
  ND2M2R g22448__1881(.A (n_286), .B (n_61), .Z (n_416));
  ND2M2R g22449__5115(.A (n_282), .B (n_60), .Z (n_406));
  OAI21M2R g22450__7482(.A1 (n_230), .A2 (n_235), .B (n_447), .Z
       (n_371));
  OAI21M2R g22452__4733(.A1 (n_231), .A2 (n_233), .B (n_446), .Z
       (n_380));
  AN2M2R g22489__9945(.A (n_244), .B (n_231), .Z (n_319));
  AN2M2R g22490__2883(.A (n_240), .B (n_230), .Z (n_327));
  DFQM2RA \bus_out_reg[9] (.CK (clk), .D (n_172), .Q (bus_out[9]));
  DFQM2RA \bus_out_reg[8] (.CK (clk), .D (n_176), .Q (bus_out[8]));
  DFQM2RA \bus_out_reg[11] (.CK (clk), .D (n_184), .Q (bus_out[11]));
  DFQM2RA \bus_out_reg[10] (.CK (clk), .D (n_171), .Q (bus_out[10]));
  MOAI22M2RA g22468__2346(.A1 (n_228), .A2 (n_13), .B1 (n_182), .B2
       (invalid_state_counter[2]), .Z (n_229));
  AOI22M2R g22474__1666(.A1 (n_219), .A2 (\L1_Cache[1] [4]), .B1
       (n_223), .B2 (\L1_Cache[3] [4]), .Z (n_227));
  AOI22M2R g22498__7410(.A1 (n_221), .A2 (\L1_Cache[0] [2]), .B1
       (n_224), .B2 (\L1_Cache[2] [2]), .Z (n_226));
  AOI22M2R g22506__6417(.A1 (n_224), .A2 (\L1_Cache[2] [7]), .B1
       (n_223), .B2 (\L1_Cache[3] [7]), .Z (n_225));
  AOI22M2R g22505__5477(.A1 (n_221), .A2 (\L1_Cache[0] [6]), .B1
       (n_224), .B2 (\L1_Cache[2] [6]), .Z (n_222));
  AOI22M2R g22504__2398(.A1 (n_219), .A2 (\L1_Cache[1] [6]), .B1
       (n_223), .B2 (\L1_Cache[3] [6]), .Z (n_220));
  AOI22M2R g22499__5107(.A1 (n_221), .A2 (\L1_Cache[0] [3]), .B1
       (n_224), .B2 (\L1_Cache[2] [3]), .Z (n_218));
  AOI22M2R g22493__6260(.A1 (n_219), .A2 (\L1_Cache[1] [0]), .B1
       (n_223), .B2 (\L1_Cache[3] [0]), .Z (n_217));
  AOI22M2R g22494__4319(.A1 (n_221), .A2 (\L1_Cache[0] [0]), .B1
       (n_224), .B2 (\L1_Cache[2] [0]), .Z (n_216));
  AOI22M2R g22495__8428(.A1 (n_219), .A2 (\L1_Cache[1] [1]), .B1
       (n_223), .B2 (\L1_Cache[3] [1]), .Z (n_215));
  AOI22M2R g22496__5526(.A1 (n_221), .A2 (\L1_Cache[0] [1]), .B1
       (n_224), .B2 (\L1_Cache[2] [1]), .Z (n_214));
  AOI22M2R g22503__6783(.A1 (n_221), .A2 (\L1_Cache[0] [5]), .B1
       (n_224), .B2 (\L1_Cache[2] [5]), .Z (n_213));
  AOI22M2R g22500__3680(.A1 (n_219), .A2 (\L1_Cache[1] [3]), .B1
       (n_223), .B2 (\L1_Cache[3] [3]), .Z (n_212));
  DFQM2RA \bus_out_reg[14] (.CK (clk), .D (n_166), .Q (bus_out[14]));
  SDFQM2RA \bus_out_reg[12] (.CK (clk), .D (bus_out[12]), .SD (n_131),
       .SE (n_130), .Q (bus_out[12]));
  NR2M2R g22487__1705(.A (n_211), .B (n_250), .Z (n_286));
  NR2M2R g22488__5122(.A (n_211), .B (n_252), .Z (n_282));
  DFQM2RA \invalid_state_counter_reg[1] (.CK (clk), .D (n_164), .Q
       (invalid_state_counter[1]));
  AOI22M2R g22507__8246(.A1 (n_221), .A2 (\L1_Cache[0] [7]), .B1
       (n_219), .B2 (\L1_Cache[1] [7]), .Z (n_210));
  CKND2M2R g22508__7098(.A (n_208), .B (n_79), .Z (n_209));
  CKND2M2R g22510__6131(.A (n_206), .B (n_76), .Z (n_207));
  CKND2M2R g22514__1881(.A (n_204), .B (n_89), .Z (n_205));
  CKND2M2R g22515__5115(.A (n_202), .B (n_91), .Z (n_203));
  AOI22M2R g22501__7482(.A1 (n_221), .A2 (\L1_Cache[0] [4]), .B1
       (n_224), .B2 (\L1_Cache[2] [4]), .Z (n_201));
  AOI22M2R g22497__4733(.A1 (n_219), .A2 (\L1_Cache[1] [2]), .B1
       (n_223), .B2 (\L1_Cache[3] [2]), .Z (n_200));
  AOI22M2R g22502__6161(.A1 (n_219), .A2 (\L1_Cache[1] [5]), .B1
       (n_223), .B2 (\L1_Cache[3] [5]), .Z (n_199));
  AO221M1RA g22527__9315(.A1 (n_196), .A2 (n_306), .B1 (n_195), .B2
       (bus_in[4]), .C (n_194), .Z (n_198));
  AO221M1RA g22528__9945(.A1 (n_196), .A2 (n_308), .B1 (n_195), .B2
       (bus_in[3]), .C (n_194), .Z (n_197));
  AO221M1RA g22532__2883(.A1 (n_196), .A2 (n_302), .B1 (n_195), .B2
       (bus_in[6]), .C (n_194), .Z (n_193));
  AO221M1RA g22533__2346(.A1 (n_196), .A2 (n_304), .B1 (n_195), .B2
       (bus_in[5]), .C (n_194), .Z (n_192));
  AO221M1RA g22534__1666(.A1 (n_196), .A2 (n_316), .B1 (n_195), .B2
       (bus_in[7]), .C (n_194), .Z (n_191));
  AO221M1RA g22536__7410(.A1 (n_196), .A2 (n_312), .B1 (n_195), .B2
       (bus_in[1]), .C (n_194), .Z (n_190));
  AO221M1RA g22537__6417(.A1 (n_196), .A2 (n_310), .B1 (n_195), .B2
       (bus_in[2]), .C (n_194), .Z (n_189));
  ND3B1M2R g22538__2398(.B (n_187), .C (resetn), .NA (n_360), .Z
       (n_267));
  ND3B1M2R g22539__5107(.B (n_186), .C (resetn), .NA (n_326), .Z
       (n_269));
  DFQM2RA \bus_out_reg[13] (.CK (clk), .D (n_165), .Q (bus_out[13]));
  ND3B1M2R g22519__6260(.B (n_185), .C (resetn), .NA (n_388), .Z
       (n_265));
  AO222M2RA g22526__4319(.A1 (n_175), .A2 (bus_out[11]), .B1 (n_174),
       .B2 (pr_addr[3]), .C1 (n_173), .C2 (bus_in[11]), .Z (n_184));
  OAI21B01M2R g22476__8428(.A1 (invalid_state_counter[2]), .A2 (n_151),
       .NB (n_182), .Z (n_183));
  ND2M2R g22509__5526(.A (n_185), .B (n_179), .Z (n_181));
  ND2M2R g22511__6783(.A (n_187), .B (n_179), .Z (n_180));
  ND2M2R g22512__3680(.A (n_186), .B (n_179), .Z (n_178));
  ND2M2R g22513__1617(.A (n_188), .B (n_179), .Z (n_177));
  CKINVM2R g22525(.A (n_233), .Z (n_244));
  CKINVM2R g22524(.A (n_235), .Z (n_240));
  DFQM2RA PrHlt_reg(.CK (clk), .D (n_152), .Q (PrHlt));
  AO222M2RA g22529__2802(.A1 (n_175), .A2 (bus_out[8]), .B1 (n_174),
       .B2 (pr_addr[0]), .C1 (n_173), .C2 (bus_in[8]), .Z (n_176));
  AO222M2RA g22530__1705(.A1 (n_175), .A2 (bus_out[9]), .B1 (n_174),
       .B2 (pr_addr[1]), .C1 (n_173), .C2 (bus_in[9]), .Z (n_172));
  AO222M2RA g22531__5122(.A1 (n_175), .A2 (bus_out[10]), .B1 (n_174),
       .B2 (pr_addr[2]), .C1 (n_173), .C2 (bus_in[10]), .Z (n_171));
  AOI221M2R g22535__8246(.A1 (n_195), .A2 (bus_in[0]), .B1 (n_196), .B2
       (n_314), .C (n_194), .Z (n_170));
  NR2M2R g22577__7098(.A (n_161), .B (n_138), .Z (n_261));
  NR2M2R g22576__6131(.A (n_348), .B (n_136), .Z (n_295));
  NR2M2R g22575__1881(.A (n_383), .B (n_142), .Z (n_298));
  NR2M2R g22574__5115(.A (n_163), .B (n_144), .Z (n_262));
  OAI21B20M2R g22516__7482(.B (n_120), .NA1 (bus_out[14]), .NA2
       (n_175), .Z (n_166));
  OAI21B20M2R g22517__4733(.B (n_129), .NA1 (bus_out[13]), .NA2
       (n_175), .Z (n_165));
  MXB2M1RA g22475__6161(.A (n_228), .B (n_146), .S
       (invalid_state_counter[1]), .Z (n_164));
  AOI21M2R g22542__9315(.A1 (n_162), .A2 (n_163), .B (n_160), .Z
       (n_233));
  AOI21M2R g22541__9945(.A1 (n_162), .A2 (n_161), .B (n_160), .Z
       (n_235));
  AOI21M2R g22540__2883(.A1 (n_162), .A2 (n_383), .B (n_160), .Z
       (n_250));
  AOI21M2R g22521__2346(.A1 (n_162), .A2 (n_348), .B (n_160), .Z
       (n_252));
  CKND2M2R g22546__1666(.A (n_296), .B (Cache_output[0]), .Z (n_159));
  INVM2R g22559(.A (n_185), .Z (n_208));
  INVM2R g22560(.A (n_187), .Z (n_204));
  INVM2R g22561(.A (n_186), .Z (n_206));
  INVM2R g22558(.A (n_188), .Z (n_202));
  AN2M2R g22579__7410(.A (n_157), .B (n_102), .Z (n_362));
  AN2M2R g22578__6417(.A (n_157), .B (n_97), .Z (n_390));
  ND2M2R g22552__5477(.A (n_175), .B (bus_out[1]), .Z (n_156));
  ND2M2R g22544__2398(.A (n_175), .B (bus_out[7]), .Z (n_155));
  ND2M2R g22545__5107(.A (n_175), .B (bus_out[6]), .Z (n_154));
  ND2M2R g22547__6260(.A (n_175), .B (bus_out[5]), .Z (n_153));
  ND2M2R g22548__4319(.A (n_126), .B (n_151), .Z (n_152));
  ND2M2R g22549__8428(.A (n_175), .B (bus_out[0]), .Z (n_150));
  ND2M2R g22550__5526(.A (n_175), .B (bus_out[2]), .Z (n_149));
  ND2M2R g22551__6783(.A (n_175), .B (bus_out[4]), .Z (n_148));
  ND2M2R g22543__3680(.A (n_175), .B (bus_out[3]), .Z (n_147));
  OAI21M2R g22518__1617(.A1 (invalid_state_counter[1]), .A2 (n_151), .B
       (n_146), .Z (n_182));
  NR2M2R g22555__2802(.A (n_143), .B (n_145), .Z (n_221));
  NR2M2R g22556__1705(.A (n_140), .B (n_145), .Z (n_219));
  NR2M2R g22554__5122(.A (n_137), .B (n_145), .Z (n_224));
  AOI21M2R g22593__8246(.A1 (n_141), .A2 (n_143), .B (n_139), .Z
       (n_144));
  AOI21M2R g22596__7098(.A1 (n_141), .A2 (n_140), .B (n_139), .Z
       (n_142));
  AOI21M2R g22597__6131(.A1 (n_141), .A2 (n_137), .B (n_139), .Z
       (n_138));
  AOI21M2R g22594__1881(.A1 (n_141), .A2 (n_133), .B (n_139), .Z
       (n_136));
  AOI21M2R g22572__5115(.A1 (n_383), .A2 (resetn), .B (n_135), .Z
       (n_187));
  AOI21M2R g22573__7482(.A1 (n_161), .A2 (resetn), .B (n_135), .Z
       (n_186));
  NR2M2R g22567__4733(.A (n_33), .B (n_134), .Z (n_281));
  NR2M2R g22569__6161(.A (n_54), .B (n_134), .Z (n_284));
  AOI21M2R g22570__9315(.A1 (n_163), .A2 (resetn), .B (n_135), .Z
       (n_188));
  AOI21M2R g22571__9945(.A1 (n_348), .A2 (resetn), .B (n_135), .Z
       (n_185));
  NR2M2R g22557__2883(.A (n_133), .B (n_145), .Z (n_223));
  NR2M2R g22581__2346(.A (n_163), .B (n_134), .Z (n_320));
  NR2M2R g22580__1666(.A (n_161), .B (n_134), .Z (n_328));
  OAI22M2R g22566__7410(.A1 (n_117), .A2 (n_118), .B1 (n_121), .B2
       (n_151), .Z (n_131));
  OAI22M2R g22568__6417(.A1 (Core_Op), .A2 (n_122), .B1 (n_124), .B2
       (n_151), .Z (n_160));
  NR2M2R g22586__5477(.A (n_141), .B (n_195), .Z (n_296));
  CKINVM2R g22592(.A (n_175), .Z (n_130));
  CKINVM2R g22591(.A (n_134), .Z (n_157));
  SDFQBM1RA \invalid_state_counter_reg[0] (.CK (clk), .D (n_125), .SD
       (n_123), .SE (invalid_state_counter[0]), .QB
       (invalid_state_counter[0]));
  NR3M2R g22610__2398(.A (n_36), .B (n_99), .C (n_128), .Z (n_196));
  ND2B1M2R g22584__5107(.B (n_47), .NA (n_129), .Z (n_145));
  ND2M2R g22585__6260(.A (n_151), .B (n_128), .Z (n_135));
  NR2M2R g22590__4319(.A (n_161), .B (n_127), .Z (n_326));
  NR2M2R g22589__8428(.A (n_383), .B (n_127), .Z (n_360));
  NR2M2R g22588__5526(.A (n_163), .B (n_127), .Z (n_318));
  NR2M2R g22587__6783(.A (n_348), .B (n_127), .Z (n_388));
  AOI32M2R g22595__3680(.A1 (n_125), .A2 (PrHlt), .A3 (n_124), .B1
       (n_114), .B2 (n_211), .Z (n_126));
  AOI21M2R g22553__1617(.A1 (n_123), .A2 (invalid_state_counter[0]), .B
       (n_125), .Z (n_146));
  NR2M2R g22604__2802(.A (n_112), .B (n_128), .Z (n_139));
  OAI21M2R g22598__1705(.A1 (n_124), .A2 (n_290), .B (n_122), .Z
       (n_162));
  OA21M2RA g22599__5122(.A1 (n_116), .A2 (n_121), .B (n_120), .Z
       (n_134));
  OA21M2RA g22600__8246(.A1 (n_115), .A2 (n_108), .B (n_119), .Z
       (n_175));
  ND2B1M2R g22583__7098(.B (n_123), .NA (invalid_state_counter[0]), .Z
       (n_228));
  INVM2R g22606(.A (n_119), .Z (n_174));
  CKINVM2R g22616(.A (n_128), .Z (n_141));
  INVM2R g22607(.A (n_127), .Z (n_194));
  ND2M2R g22602__6131(.A (n_118), .B (n_113), .Z (n_120));
  MAOI22M2RA g22608__1881(.A1 (n_117), .A2 (n_111), .B1 (n_116), .B2
       (n_115), .Z (n_129));
  AOI21M2R g22603__5115(.A1 (n_109), .A2 (n_110), .B (n_115), .Z
       (n_173));
  INVM2R g22601(.A (n_123), .Z (n_151));
  AOI21M2R g22609__7482(.A1 (n_117), .A2 (resetn), .B (n_118), .Z
       (n_119));
  INVM1R g22615(.A (n_114), .Z (n_122));
  ND2M2R g22618__4733(.A (n_125), .B (n_121), .Z (n_128));
  ND3M2R g22612__6161(.A (n_118), .B (n_113), .C (n_121), .Z (n_127));
  AN3M2R g22611__9315(.A (n_118), .B (n_112), .C (n_121), .Z (n_195));
  NR2M2R g22605__9945(.A (n_113), .B (n_290), .Z (n_123));
  NR2M2R g22617__2883(.A (n_124), .B (n_116), .Z (n_114));
  CKINVM2R g22613(.A (n_290), .Z (n_118));
  CKINVM2R g22619(.A (n_116), .Z (n_125));
  NR2B1M2R g22620__2346(.B (n_111), .NA (n_110), .Z (n_116));
  ND2M2R g22621__1666(.A (n_111), .B (n_121), .Z (n_109));
  AO21M2RA g22614__7410(.A1 (n_106), .A2 (n_103), .B (n_108), .Z
       (n_290));
  NR2M2R g22623__6417(.A (n_107), .B (n_105), .Z (n_111));
  OR2M2R g22624__5477(.A (n_107), .B (n_104), .Z (n_110));
  ND2M2R g22622__2398(.A (n_105), .B (n_104), .Z (n_106));
  AN2M2R g22626__5107(.A (n_104), .B (Core_Op), .Z (n_117));
  ND2M2R g22635__6260(.A (n_103), .B (resetn), .Z (n_107));
  AOI211M2R g22625__4319(.A1 (n_88), .A2 (n_102), .B (n_92), .C (n_94),
       .Z (n_105));
  AOI32M2R g22627__8428(.A1 (n_68), .A2 (\Cache_Status[2] [1]), .A3
       (n_161), .B1 (n_87), .B2 (n_238), .Z (n_101));
  AOI32M2R g22628__5526(.A1 (n_70), .A2 (\Cache_Status[0] [1]), .A3
       (n_163), .B1 (n_84), .B2 (n_242), .Z (n_100));
  AOI221M2R g22643__6783(.A1 (n_112), .A2 (n_37), .B1 (n_99), .B2
       (n_34), .C (n_450), .Z (n_103));
  NR2M2R g22629__3680(.A (n_95), .B (n_93), .Z (n_104));
  AOI32M2R g22631__1617(.A1 (n_67), .A2 (\Cache_Status[3] [1]), .A3
       (n_348), .B1 (n_81), .B2 (n_97), .Z (n_98));
  AOI32M2R g22630__2802(.A1 (n_71), .A2 (\Cache_Status[1] [1]), .A3
       (n_383), .B1 (n_80), .B2 (n_102), .Z (n_96));
  OAI21M2R g22636__1705(.A1 (n_163), .A2 (n_83), .B (n_85), .Z (n_95));
  OAI22M2R g22632__5122(.A1 (n_163), .A2 (n_90), .B1 (n_161), .B2
       (n_75), .Z (n_94));
  OAI21M2R g22634__8246(.A1 (n_161), .A2 (n_86), .B (n_74), .Z (n_93));
  OAI221M2R g22638__7098(.A1 (n_348), .A2 (n_77), .B1 (n_29), .B2
       (n_78), .C (n_99), .Z (n_92));
  OAI21M2R g22633__6131(.A1 (n_163), .A2 (n_99), .B (n_90), .Z (n_91));
  AO21M2RA g22637__1881(.A1 (n_112), .A2 (n_102), .B (n_88), .Z (n_89));
  CKND2M2R g22640__5115(.A (n_86), .B (n_85), .Z (n_87));
  CKND2M2R g22641__7482(.A (n_83), .B (n_85), .Z (n_84));
  OAI21B20M2R g22639__6161(.B (n_85), .NA1 (\Cache_Status[3] [1]), .NA2
       (n_72), .Z (n_81));
  OAI21B20M2R g22642__9315(.B (n_85), .NA1 (\Cache_Status[1] [1]), .NA2
       (n_73), .Z (n_80));
  OAI221M2R g22644__9945(.A1 (n_348), .A2 (n_99), .B1 (n_133), .B2
       (n_78), .C (n_77), .Z (n_79));
  OAI221M2R g22645__2883(.A1 (n_161), .A2 (n_99), .B1 (n_137), .B2
       (n_78), .C (n_75), .Z (n_76));
  AOI33M2R g22646__2346(.A1 (n_73), .A2 (\Cache_Status[1] [1]), .A3
       (n_102), .B1 (n_72), .B2 (\Cache_Status[3] [1]), .B3 (n_97), .Z
       (n_74));
  MOAI22M2RA g22647__1666(.A1 (n_78), .A2 (n_140), .B1 (n_71), .B2
       (\Cache_Status[1] [0]), .Z (n_88));
  MAOI22M2RA g22648__7410(.A1 (n_70), .A2 (\Cache_Status[0] [0]), .B1
       (n_78), .B2 (n_143), .Z (n_90));
  AOI31M2R g22660__6417(.A1 (n_451), .A2 (\tag_directory[1] [1]), .A3
       (n_102), .B (n_62), .Z (n_69));
  ND2M2R g22653__5477(.A (n_66), .B (\Cache_Status[2] [1]), .Z (n_86));
  ND2M2R g22652__2398(.A (n_65), .B (\Cache_Status[0] [1]), .Z (n_83));
  CKND2M2R g22649__5107(.A (n_68), .B (\Cache_Status[2] [0]), .Z
       (n_75));
  CKND2M2R g22650__6260(.A (n_67), .B (\Cache_Status[3] [0]), .Z
       (n_77));
  OAI21M2R g22658__4319(.A1 (n_59), .A2 (n_64), .B (n_63), .Z (n_66));
  OAI21M2R g22659__8428(.A1 (n_55), .A2 (n_64), .B (n_63), .Z (n_65));
  OAI32M2R g22664__5526(.A1 (pr_addr[3]), .A2 (n_30), .A3 (n_112), .B1
       (n_38), .B2 (n_99), .Z (n_62));
  OAI21M2R g22662__6783(.A1 (n_61), .A2 (n_64), .B (n_63), .Z (n_73));
  OAI21M2R g22661__3680(.A1 (n_60), .A2 (n_64), .B (n_63), .Z (n_72));
  CKND2M2R g22654__1617(.A (n_58), .B (n_59), .Z (n_68));
  ND2M2R g22655__2802(.A (n_58), .B (n_60), .Z (n_67));
  ND2M2R g22657__1705(.A (n_58), .B (n_61), .Z (n_71));
  ND2M2R g22656__5122(.A (n_58), .B (n_55), .Z (n_70));
  ND2M2R g22671__8246(.A (n_112), .B (Core_Op), .Z (n_85));
  NR2M2R g22665__6131(.A (n_53), .B (n_449), .Z (n_63));
  NR2M2R g22663__1881(.A (n_53), .B (n_51), .Z (n_58));
  INVM2R g22672(.A (n_99), .Z (n_112));
  ND2M2R g22667__7482(.A (n_50), .B (n_124), .Z (n_51));
  OAI221M2R g22670__4733(.A1 (n_43), .A2 (PrHlt), .B1 (n_9), .B2
       (n_48), .C (n_46), .Z (n_53));
  OR2M1R g22673__6161(.A (n_211), .B (n_124), .Z (n_99));
  AOI21M2R g22674__9315(.A1 (n_49), .A2 (bus_in[13]), .B (bus_in[14]),
       .Z (n_50));
  NR2B1M2R g22675__9945(.B (n_49), .NA (n_48), .Z (n_64));
  ND3B1M2R g22677__2883(.B (n_49), .C (n_47), .NA (n_45), .Z (n_115));
  ND3M2R g22676__2346(.A (PrHlt), .B (n_44), .C (n_46), .Z (n_124));
  ND2M2R g22678__1666(.A (n_49), .B (n_6), .Z (n_78));
  ND3B1M2R g22682__7410(.B (n_40), .C (n_42), .NA (n_45), .Z (n_48));
  CKINVM2R g22680(.A (n_43), .Z (n_44));
  NR3B1M2R g22679__6417(.B (n_42), .C (n_41), .NA (n_46), .Z (n_49));
  AOI21M2R g22681__5477(.A1 (n_45), .A2 (n_42), .B (n_41), .Z (n_43));
  INVM1R g22684(.A (n_41), .Z (n_40));
  CKND2M2R g22685__2398(.A (n_31), .B (n_35), .Z (n_41));
  ND2M1R g22683__5107(.A (n_39), .B (resetn), .Z (n_272));
  NR2M1R g22686__6260(.A (n_108), .B (n_39), .Z (n_179));
  NR3M1R g22688__4319(.A (n_38), .B (n_37), .C (n_36), .Z (n_39));
  XNR2M2RA g22689__8428(.A (n_452), .B (n_8), .Z (n_35));
  MXB2M1RA g22687__5526(.A (pr_addr[2]), .B (n_33), .S (n_452), .Z
       (n_34));
  XOR2M2RA g22690__6783(.A (n_30), .B (n_5), .Z (n_31));
  AOI221M2R g22692__3680(.A1 (\Cache_Status[2] [0]), .A2 (n_59), .B1
       (\Cache_Status[3] [0]), .B2 (n_60), .C (n_454), .Z (n_45));
  OA221M1RA g22695__2802(.A1 (n_163), .A2 (n_143), .B1 (n_140), .B2
       (n_383), .C (n_29), .Z (n_36));
  NR2M2R g22696__1705(.A (n_19), .B (n_20), .Z (n_42));
  NR2M2R g22691__5122(.A (n_21), .B (n_14), .Z (n_30));
  AOI222M1RA g22694__6131(.A1 (\tag_directory[0] [1]), .A2 (n_242), .B1
       (\tag_directory[2] [1]), .B2 (n_238), .C1 (\tag_directory[3]
       [1]), .C2 (n_97), .Z (n_26));
  NR2M1R g22698__5115(.A (n_140), .B (n_211), .Z (n_24));
  NR2M1R g22699__7482(.A (n_133), .B (n_211), .Z (n_23));
  NR2M1R g22700__4733(.A (n_383), .B (n_211), .Z (n_22));
  OAI22M2R g22709__6161(.A1 (n_163), .A2 (\tag_directory[0] [1]), .B1
       (n_161), .B2 (\tag_directory[2] [1]), .Z (n_21));
  NR2M1R g22702__9315(.A (n_143), .B (n_211), .Z (n_231));
  NR2M1R g22701__9945(.A (n_137), .B (n_211), .Z (n_230));
  AO22M1RA g22705__2883(.A1 (\Cache_Status[2] [1]), .A2 (n_59), .B1
       (\Cache_Status[3] [1]), .B2 (n_60), .Z (n_20));
  AO22M1RA g22708__2346(.A1 (\Cache_Status[0] [1]), .A2 (n_55), .B1
       (\Cache_Status[1] [1]), .B2 (n_61), .Z (n_19));
  NR2M1R g22697__1666(.A (n_348), .B (n_211), .Z (n_18));
  AOI22M1R g22712__7410(.A1 (n_238), .A2 (n_59), .B1 (n_60), .B2
       (n_97), .Z (n_29));
  NR2M1R g22704__6417(.A (n_163), .B (n_211), .Z (n_243));
  NR2M1R g22703__5477(.A (n_161), .B (n_211), .Z (n_239));
  OAI22M2R g22706__6260(.A1 (n_383), .A2 (\tag_directory[1] [1]), .B1
       (n_348), .B2 (\tag_directory[3] [1]), .Z (n_14));
  CKINVM1R g22725(.A (n_402), .Z (n_312));
  NR3B1M2R g22723__4319(.B (invalid_state_counter[3]), .C (n_13), .NA
       (invalid_state_counter[0]), .Z (n_113));
  CKINVM1R g22730(.A (n_394), .Z (n_302));
  CKINVM1R g22727(.A (n_409), .Z (n_316));
  CKINVM1R g22731(.A (n_400), .Z (n_310));
  CKINVM1R g22726(.A (n_398), .Z (n_306));
  CKINVM1R g22728(.A (n_404), .Z (n_314));
  CKINVM1R g22729(.A (n_407), .Z (n_308));
  CKINVM1R g22732(.A (n_396), .Z (n_304));
  AOI22M1R g22733__3680(.A1 (n_3), .A2 (n_4), .B1 (bus_in[12]), .B2
       (bus_in[13]), .Z (n_9));
  OAI22M1R g22735__1617(.A1 (bus_in[10]), .A2 (n_33), .B1 (pr_addr[2]),
       .B2 (n_8), .Z (n_37));
  AOI22M1R g22738__2802(.A1 (n_121), .A2 (bus_in[7]), .B1 (Core_Op),
       .B2 (Cache_input[7]), .Z (n_409));
  AOI22M1R g22740__1705(.A1 (n_121), .A2 (bus_in[3]), .B1 (Core_Op),
       .B2 (Cache_input[3]), .Z (n_407));
  AOI22M1R g22741__5122(.A1 (n_121), .A2 (bus_in[6]), .B1 (Core_Op),
       .B2 (Cache_input[6]), .Z (n_394));
  AOI22M1R g22742__8246(.A1 (n_121), .A2 (bus_in[2]), .B1 (Core_Op),
       .B2 (Cache_input[2]), .Z (n_400));
  AOI22M1R g22743__7098(.A1 (n_121), .A2 (bus_in[5]), .B1 (Core_Op),
       .B2 (Cache_input[5]), .Z (n_396));
  NR2B1M1R g22714__1881(.B (bus_in[12]), .NA (n_47), .Z (n_6));
  AOI22M1R g22734__5115(.A1 (n_5), .A2 (n_54), .B1 (bus_in[11]), .B2
       (pr_addr[3]), .Z (n_38));
  AOI22M1R g22739__7482(.A1 (n_121), .A2 (bus_in[0]), .B1 (Core_Op),
       .B2 (Cache_input[0]), .Z (n_404));
  AOI22M1R g22736__4733(.A1 (n_121), .A2 (bus_in[1]), .B1 (Core_Op),
       .B2 (Cache_input[1]), .Z (n_402));
  AOI22M1R g22737__6161(.A1 (n_121), .A2 (bus_in[4]), .B1 (Core_Op),
       .B2 (Cache_input[4]), .Z (n_398));
  CKINVM1R g22753(.A (n_59), .Z (n_137));
  CKINVM1R g22754(.A (n_61), .Z (n_140));
  OR3M2R g22724__9315(.A (bus_in[14]), .B (n_4), .C (n_3), .Z (n_211));
  OA21M1RA g22722__9945(.A1 (bus_in[16]), .A2 (bus_in[15]), .B
       (flag_in), .Z (n_46));
  INVM1R g22745(.A (n_133), .Z (n_60));
  NR2M1R g22759__2883(.A (bus_in[9]), .B (n_1), .Z (n_61));
  CKINVM1R g22755(.A (n_383), .Z (n_102));
  CKINVM1R g22747(.A (n_242), .Z (n_163));
  ND3B1M2R g22721__2346(.B (invalid_state_counter[2]), .C
       (invalid_state_counter[1]), .NA (invalid_state_counter[3]), .Z
       (n_2));
  CKINVM1R g22744(.A (n_55), .Z (n_143));
  CKINVM1R g22746(.A (n_348), .Z (n_97));
  INVM1R g22756(.A (n_161), .Z (n_238));
  NR2M1R g22758__1666(.A (bus_in[8]), .B (n_0), .Z (n_59));
  NR2M1R g22752__7410(.A (pr_addr[0]), .B (pr_addr[1]), .Z (n_242));
  ND2B1M1R g22760__6417(.B (pr_addr[0]), .NA (pr_addr[1]), .Z (n_383));
  ND2M2R g22751__5477(.A (pr_addr[1]), .B (pr_addr[0]), .Z (n_348));
  ND2B1M2R g22761__2398(.B (pr_addr[1]), .NA (pr_addr[0]), .Z (n_161));
  ND2B1M2R g22748__5107(.B (invalid_state_counter[1]), .NA
       (invalid_state_counter[2]), .Z (n_13));
  NR2M1R g22757__6260(.A (bus_in[13]), .B (bus_in[14]), .Z (n_47));
  NR2M1R g22749__4319(.A (bus_in[8]), .B (bus_in[9]), .Z (n_55));
  ND2M1R g22750__8428(.A (bus_in[9]), .B (bus_in[8]), .Z (n_133));
  CKINVM1R g22764(.A (bus_in[8]), .Z (n_1));
  CKINVM1R g22770(.A (bus_in[11]), .Z (n_5));
  CKINVM1R g22766(.A (bus_in[10]), .Z (n_8));
  CKINVM1R g22771(.A (resetn), .Z (n_108));
  INVM2R g22767(.A (Core_Op), .Z (n_121));
  CKINVM1R g22763(.A (bus_in[9]), .Z (n_0));
  CKINVM1R g22768(.A (bus_in[13]), .Z (n_3));
  CKINVM1R g22762(.A (bus_in[12]), .Z (n_4));
  CKINVM1R g22765(.A (pr_addr[3]), .Z (n_54));
  CKINVM1R g22769(.A (pr_addr[2]), .Z (n_33));
  ND2B1M2R g2(.B (n_252), .NA (n_390), .Z (n_444));
  ND2B1M2R g22848(.B (n_250), .NA (n_362), .Z (n_445));
  ND2B1M2R g22849(.B (n_233), .NA (n_320), .Z (n_446));
  ND2B1M2R g22850(.B (n_235), .NA (n_328), .Z (n_447));
  ND3B1M1R g22851(.B (n_188), .C (resetn), .NA (n_318), .Z (n_448));
  OAI21B10M2R g22852(.A1 (n_124), .B (n_50), .NA2 (n_211), .Z (n_449));
  OA31M2RA g22853(.A1 (n_54), .A2 (n_112), .A3 (n_26), .B (n_69), .Z
       (n_450));
  NR2M2R g22668__22854(.A (n_54), .B (n_112), .Z (n_451));
  AOI221M2R g22855(.A1 (\tag_directory[2] [0]), .A2 (n_238), .B1
       (\tag_directory[0] [0]), .B2 (n_242), .C (n_453), .Z (n_452));
  AO22M1RA g22856(.A1 (\tag_directory[1] [0]), .A2 (n_102), .B1
       (\tag_directory[3] [0]), .B2 (n_97), .Z (n_453));
  AO22M1RA g22857(.A1 (\Cache_Status[1] [0]), .A2 (n_61), .B1
       (\Cache_Status[0] [0]), .B2 (n_55), .Z (n_454));
endmodule

